name: kpconv
channels:
  - open3d-admin
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py36_0
  - astor=0.7.1=py36_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=2.14=openblas
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py36_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.6.0=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.5=he1b5a44_1004
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gast=0.2.2=py36_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_1
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.10.0=nompi_py36h513d04c_102
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.7.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.0=py_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.0=hc9558a2_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm9=9.0.0=hc9558a2_2
  - libopenblas=0.3.7=h5ec1e0e_6
  - libopencv=4.2.0=py36_2
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.8.0=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.9=hee79883_5
  - lz4-c=1.8.3=he1b5a44_1001
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36he7580a8_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mkl_fft=1.1.0=py36hc1659b7_1
  - mkl_random=1.1.0=py36hb3f55d8_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - notebook=6.0.0=py36_0
  - nspr=4.23=he1b5a44_0
  - nss=3.46=he751ad9_0
  - numpy=1.18.1=py36h95a1406_0
  - numpy-base=1.18.1=py36h2f8d375_1
  - open3d=0.7.0.0=py36_0
  - opencv=4.2.0=py36_2
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h516909a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.0=py_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.8.0=py36he6710b0_0
  - psutil=5.6.3=py36h7b6447c_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_0
  - py-opencv=4.2.0=py36h5ca1d4c_2
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.12.3=py36hcca6a23_0
  - pyrsistent=0.14.11=py36h7b6447c_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.12.5=h0c104cb_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py36hcdab131_1
  - scipy=1.4.1=py36h921218d_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he68c306_0
  - tensorflow-base=1.12.0=gpu_py36h8e0ae2d_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.9=hed695b0_1003
  - tornado=6.0.3=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.0=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - cvxpy==1.0.25
    - dill==0.3.1.1
    - ecos==2.0.7.post1
    - future==0.18.2
    - multiprocess==0.70.9
    - osqp==0.6.1
    - pclkeypoint==0.0.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - scs==2.1.1-2
prefix: /home/xybai/anaconda3/envs/kpconv

